config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sessions#login'
  
  #root 'pages#home'
  get '/home', to:  'pages#home'
  # User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  # Session routes
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/waiting4approval', to: 'sessions#waiting4approval'
  get '/riattiva', to: 'sessions#riattiva'
  get '/utenti', to: 'users#list'
  get '/history', to: 'users#showHistory'
  get '/commenti', to: 'users#showCommenti'
  post '/saveCommenti', to: 'users#saveCommenti'

  resource :tasks do
    get 'filter_apt', on: :member
    get 'clear', on: :member
    get 'history', on: :member
    get 'view', on: :member
    get 'commenti', on: :member
    post 'saveCommenti', on: :member
  end
  resources :tasks,  except:  [:index, :show] 
  resources :stati_richiesta,  except:  [:index, :show] 

end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery with: :null_session

def new
  #puts "Matteo --> New Task Modal Window"
  @task = Task.new
  @task.email = $user.email
  @apts = $apts #Appartamenti.all.map(&:apt) #.map(|apt| apt.apt)
  puts @apts.inspect
end

def view
  @task = Task.find(params[:format])
  puts "TASK: "+ @task.inspect
end
  
def clear
  #puts "Matteo --> Clear List"
  Task.destroy_all
  redirect_to '/home'
end

def edit #Quando premuto il pulsante die EDIT dalla lista
  puts params.inspect
  #puts "Matteo --> Edit ToDo"
  @task = Task.find(params[:format])
  #@tasks = Task.all
end
  
def destroy
  #puts "Matteo --> Remove ToDo"
  Task.find(params[:id]).destroy
  if $is_gestore
    @apts = $apts
    @tasks = Task.all
  else
    @apts = []
    @tasks = Task.where('apt = "' + $user[:apt] + '"')
  end
 #redirect_to '/home'
end

def create
  puts params.inspect
  myP = {}
  myP = task_params
  myP[:email] = $user[:email]
  if(!$is_gestore)
    myP[:apt] = $user[:apt]
  end
  #puts "Matteo --> Create New Task with params: #{myP}"
  @task = Task.create(myP)
  AddRecord(@task, 'history', 'STATO  --> NEW (registrazione nuova Richiesta)')
  @tasks = Task.where('apt = "' + $user[:apt] + '"')
  @apts = nil
  if $is_gestore
    @tasks = Task.all
    @apts = Task.select(:apt).map(&:apt).uniq #calcola la lista degli APT presenti nelle Richieste attive
    @apts.push('tutti') #aggiungi la lista completa
  end
  redirect_to '/home'
end

def filter_apt
  params[:sort] ||= 'created_at'       #definisco il valore di default
  params[:direction] ||= 'asc'  #definisco il valore di default
  if(params[:apt] == 'tutti')
    @tasks = Task.all.order(params[:sort] + ' ' + params[:direction]) #lista ordinata  
  else
    @tasks = Task.where('apt = "' + params[:apt] + '"').order(params[:sort] + ' ' + params[:direction]) #lista ordinata  
  end
    @apts = Task.select(:apt).map(&:apt).uniq #calcola la lista degli APT presenti nelle Richieste attive
    @apts.push('tutti') #aggiungi la lista completa
end

def update #Richiamata quando utente modifica la Richiesta
  #puts "Matteo --> Update Task with params: #{params[:id]}"
  task = Task.find(params[:id])

  puts task_params.inspect
  puts task_params[:apt]
  puts task.apt

  #puts 'URGENZA: ' 
  #puts task.urgenza && task.urgenza.strftime("%e/%m/%Y") 
  #puts task_params[:urgenza]
  if task.urgenza != task_params[:urgenza]
    #puts "UPDATING: URGENZA"
    AddRecord(task, 'history', 'URGENZA ' + task.urgenza + ' --> ' + task_params[:urgenza])
    task.urgenza = task_params[:urgenza]
  end
  
  if(task.oggetto != task_params[:oggetto])
    AddRecord(task, 'history', 'OGGETTO '+ task.oggetto + ' --> ' + task_params[:oggetto])
    task.oggetto = task_params[:oggetto]
  end
  
  if(task.richiesta != task_params[:richiesta])
    AddRecord(task, 'history', 'RICHIESTA '+ task.richiesta + ' --> ' + task_params[:richiesta])
    task.richiesta = task_params[:richiesta]
  end
  
  if(task.stato != task_params[:stato])
    AddRecord(task, 'history', 'STATO '+ task.stato + ' --> ' + task_params[:stato])
    task.stato = task_params[:stato]
  end
  
  if !!task_params[:apt] && (task.apt != task_params[:apt]) #il gestore potrebbe cambiare l'appartamento
    AddRecord(task, 'history', 'APT '+ task.apt + ' --> ' + task_params[:apt])
    task.apt = task_params[:apt]
  end
  
  task.save
  redirect_to '/home'
end

  def history
    #puts "SHOW-HISTORY(params): #{params.inspect} #{params[:format]}"
    task = Task.find(params[:format])
    @history = task.history
  end

  def commenti
    #puts "SHOW-COMMENTI(params): #{params.inspect} #{params[:format]}"
    @task = Task.find(params[:format])
    #AddRecord(@task, 'commenti', "balle belle")
    taskComments = []
    @comments = []
    #taskComments = @task.commenti.scan(/.*\n\n/m)
    if (!@task.commenti) 
      @task.commenti = ""
    end
    taskComments = @task.commenti.split("\n\n") #separo un commento dall'altro in un array
    #puts "TASK-COMMENTS:"
    #puts taskComments.inspect
    # per ogni commento genero l'oggetto estrapolando le varie informazioni
    taskComments.each() {|c| 
      c += "\n" # inserisco un "newline" nel caso, per motivi storici, il campo del DB contenga commenti non formattati correttamente
      head = c.match(/.*\n/)[0] # ricavo l'informazione HEAD contenuta nella prima riga
      @comments.push({
        author: head.gsub(/.* by (.*)\n/,'\1'),  # estraggo l'autore da HEAD
        head: head,                      # inserisco HEAD
        body: c.gsub(head, '')           # ricavo il commento vero e proprio rimuovendo la prima riga    <% end %>    <% end %>


      })
    }
    #puts 'MP --> ' + @comments.inspect
  end

  def saveCommenti
    #puts "SAVE-COMMENTI(params): #{params.inspect} #{params[:DELbutton]} #{params[:taskID]} #{params[:commento]} #{params[:comN]}"
    @task = Task.find(params[:ID])
    #puts "SAVE-COMMENTI(task): #{@task.inspect}"
    if(params[:comN] != 'NEW') 
      #puts "SAVING MODIFIED COMMENT N. #{params[:comN]}"
      n = params[:comN].to_i
      del = params[:DELbutton]
      taskComments = []
      taskComments = @task.commenti.scan(/.*\n.*\n\n/)
      #puts taskComments.inspect
      commenti = ""
      taskComments.each_with_index() {|c, i| 
        if(i != n) 
          puts "i: " + i.to_s + "n: " + n.to_s
          commenti += c
        else
          puts "DELETING: " + c
        end
      }
      @task.commenti = commenti
    end
    #puts "COMMENTI: " 
    #puts @task.commenti
    if(del != 'DEL')
      AddRecord(@task, 'commenti', params[:commento])
    else
      @task.save
    end
    redirect_to '/home'
  end
  
# private methods
private
def task_params
  params.require(:task).permit(:oggetto, :richiesta, :urgenza, :stato, :apt)
end

def AddRecord(rec, type, text)
  puts "ADD-RECORD: " + text
  #puts text
  #puts "AUTHOR: #{$user.email}" + $user.inspect
  if(! rec[type]) then rec[type] = "" end
  rec[type] = DateTime.now.strftime("%d/%m/%Y  %I:%M%p") + " by " + $user[:email] + "\n" + text.gsub(/\n\n+/,'\n') + "\n\n" + rec[type]
  rec.save
end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_commenti.html.erb
<div class="container" style="padding: 100px;  background-color: coral; text-align: center">
<table>
<tbody>
<tr>
  <td>
    <div id="commenti" style="margin-top: 70px; width: 500px; height: 500px; overflow: auto">
      <div style="margin: 5px; padding: 5px; border-style: solid; border-color: blue; border-radius: 5px; background-color: lightseagreen; text-align: center;">
        <button style="display: inline; width: 100%" onclick="myNew()" >NEW</button>
      </div>
        
        <% comments.each_with_index do |commento, idx| %>  
          <% if(commento[:author] == $user.email) %>
            <div onclick="myFunction(event, this)" id="<%= idx %>" style="margin: 5px; padding: 5px; border-style: solid; border-color: blue; border-radius: 5px; background-color: lightseagreen">
          <% else %>
            <div style="margin: 5px; padding: 5px; border-style: solid; border-color: blue; border-radius: 5px; background-color: lightseagreen">
          <% end %>
            <div style="background-color: lightgray"><%= commento[:head] %></div>
            <div style="background-color: lightblue"><%= commento[:body] %></div>
          </div>
        <% end %>
    </div>
  </td>
  <td>
    <form action="<%= controller %>/saveCommenti" method="POST">
      <!--button id="dell"  type="submit" style="display: none" >DEL</button>
      <button type="submit" >SAVEE</button-->
<input type="submit" name="SAVEbutton" value="SAVE" />
<input type="submit" id="del" name="DELbutton" style="display: none" value="DEL" />
      <div>
      <textarea id="edit" name="commento" data-remote="true" rows="20" cols="40">
      </textarea>
      <input type="hidden" name="ID" value="<%= elemento.id %>">
      <input type="hidden" id="comN" name="comN" value="NEW">
      </div>
    </form>
  </td>
</tr>
</tbody>
</table>
</div>

app/views/tasks/_dettagli.html.erb
<%# 
Visualizza, modifica e permette l'inserimento dei dettagli di una Richiesta 
a secoda del valore passato mediante le variabili locali  is_view, is_update, is_new] 
%>
<div class="container" style="padding: 30px;  background-color: coral; text-align: center">
  <% if is_new %>
    <h1>Nuova Richiesta</h1>
  <% elsif is_update %>
    <h1>Modifica Richiesta</h1>
    <h3>richiedente: <%= task.email %></h3>
  <% else %>
    <h1>Visiona i dettagli della Richiesta</h1>
    <h3>richiedente: <%= task.email %></h3>
  <% end %>
  <hr>
<%= simple_form_for task, class: 'clearfix', remote: true  do |f| %>
  <div style="font-size: 20px">
    <%= f.text_field :oggetto, size: "28", value: task.oggetto, :disabled => is_view %>
      <hr>
    <%= f.text_area :richiesta, size: "50x10", value: task.richiesta, :disabled => is_view %>
    <%= f.hidden_field :stato, :value => "new" %>
    <%= f.input :urgenza, as: :string, :label => "Data Desiderata  _", style: 'margin-left: 10px;  display: inline;', input_html: {value: task.urgenza, class: 'datepicker', size: 8, :disabled => is_view} %> 
      <hr>
    <% if $is_gestore && task.email == $user.email && !is_view%>
      <%= f.select(:apt, apts, :selected => task.apt) %>
    <% end %>
    <% if(!is_view) %>
      <%= f.submit 'Save', class: 'btn btn-primary', style: 'display: inline;' %>
    <% end %>
</div>
<% end %>
<script>

$( document ).ready(function() {
    $('.datepicker').datepicker({format: "dd-mm-yyyy"});
});

</script>

app/views/tasks/_history.html.erb
<textarea readonly style="width: 700px; height: 700px">
<%= @history %>
</textarea>

app/views/tasks/_task_list.html.erb
<div class="container">
  <% if(apts != nil) %>
    <%= form_with url: "/tasks/filter_apt", method: :get, remote: true  do |f| %>
      <%= f.select(:apt, apts, {:selected => params[:apt] || 'tutti'}, {:onchange => 'this.form.submit()', class: "form-control"}) %>
    <% end %>
  <% end %>
  
  <% if !tasks %>
    <span class="text-warning">NON CI SONO RICHIESTE!</span>
  <% else %>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th><%= sortable "oggetto"%></th>
          <th>APT</th>
          <th><%= sortable "created_at", "data"%></th>
          <th><%= sortable "urgenza"%></th>
          <th><%= sortable "stato"%></th>
          <th>Azioni</th>
        </tr>
      </thead>
      <tbody>
        <% tasks.each do |task| %>
          <tr>
            <td>
              <strong>
                <%= link_to view_tasks_path(task), remote: true do %>  <i class="fa fa-eye"></i><% end %>
                <%= task.oggetto %>
              </strong>
            </td>
            <td class="text-info">
              <%= task.apt %>
            </td>
            <td class="text-info">
              <%= task.created_at %>
            </td>
            <td class="text-success">
              <%= task.urgenza.to_s %>
            </td>
            <td class="text-success">
              <% if $is_gestore %>
                <%= simple_form_for task, class: 'clearfix', remote: true  do |f| %>
                  <%= f.select(:stato, stati, {}, {:onchange => 'this.form.submit()', class: "form-control"}) %>
                <% end %>
              <% else %>
                <%= task.stato %>
              <% end %>
            </td>
            <td class="text-success" style="font-size:24px">
              <% if task.email == $user[:email] || $is_admin %>
                <%= link_to task_path(task), method: :delete, remote: true, data: {confirm: "Are you sure you want to delete task #{task.oggetto}?"} do %>  <i class="fa fa-trash"></i><% end %>                
                <%= link_to edit_tasks_path(task), remote: true do %>  <i class="fa fa-pencil-square-o"></i><% end %>
              <% end %>
              <%= link_to history_tasks_path(task), remote: true do %>  <i class="fa fa-history"></i><% end %>
              <%= link_to commenti_tasks_path(task), remote: true do %>  <i class="fa fa-commenting-o"></i><% end %>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/tasks/clear.js.erb
m.html('<%= j(render partial: 'task_list', locals: {stati: $stati, tasks: [], apts: []}) %>');

app/views/tasks/commenti.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'commenti', locals: {comments: @comments, elemento: @task, controller: 'tasks'}) %>');
m.modal('show');

  
function myFunction(p1, p2) {
  document.querySelector('#edit').value = p2.children.item(1).innerHTML;
  selected = document.querySelector('.selected');
  if(selected) {
    selected.style.backgroundColor = "blue";
    selected.classList.remove("selected");
  }
  p2.style.backgroundColor = "red";
  p2.classList.add("selected");
  document.querySelector('#comN').value = p2.id;
  document.querySelector('#del').style.display = "inline";
}


function myNew() {
  document.querySelector('#comN').value = 'NEW'; 
  document.querySelector('#del').style.display = "none";
  selected = document.querySelector('.selected');
  if(selected) {
    selected.style.backgroundColor = "blue";
    selected.classList.remove("selected");
  }
  document.querySelector('#edit').value = "";
}

app/views/tasks/destroy.js.erb
window.location.assign("/home")

app/views/tasks/edit.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'dettagli', locals: {task: @task, apts: $apts, is_new: false, is_update: true, is_view: false}) %>');
m.modal('show');

app/views/tasks/filter_apt.html.erb
 <%= render partial: 'tasks/task_list', locals: {stati: $stati, tasks: @tasks, apts: @apts} %>

app/views/tasks/history.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'history', locals: {task: @task}) %>');
m.modal('show');

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'dettagli', locals: {task: @task, apts: @apts, is_new: true, is_update: false, is_view: false}) %>');
m.modal('show');

app/views/tasks/nnew.html.erb
<div class="modal-header">
  <h1>New Task</h1>
</div>
<%= simple_form_for @task, class: 'clearfix' do |f| %>
  <div class="modal-body">
    <%= f.input :title %>
    <%= f.input :note %>
    <%= f.input :completed, as: :string, input_html: {class: 'datepicker'} %>  </div>
  <div class="modal-footer">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>
<script>

$( document ).ready(function() {
    $('.datepicker').datepicker();
});

</script>

app/views/tasks/show.js.erb
$('#task-list').html('<%= j(Task.destroy_all) %>');
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: Task.all}) %>');

app/views/tasks/view.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'dettagli', locals: {task: @task, apts: $apts, is_new: false, is_update: false, is_view: true}) %>');
m.modal('show');