config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'sessions#login'
  
  #root 'pages#home'
  get '/home', to:  'pages#home'
  # User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  # Session routes
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/waiting4approval', to: 'sessions#waiting4approval'
  get '/riattiva', to: 'sessions#riattiva'
  get '/utenti', to: 'users#list'
  get '/history', to: 'users#showHistory'
  get '/commenti', to: 'users#showCommenti'
  post '/saveCommenti', to: 'users#saveCommenti'

  resource :tasks do
    get 'filter_apt', on: :member
    get 'clear', on: :member
    get 'history', on: :member
    get 'view', on: :member
    get 'commenti', on: :member
    post 'saveCommenti', on: :member
  end
  resources :tasks,  except:  [:index, :show] 
  resources :stati_richiesta,  except:  [:index, :show] 

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #protect_from_forgery with: 
  skip_before_action :verify_authenticity_token
  skip_before_action :authorize, only: [:new, :create]
  before_action :is_admin, only: [:list]
  
  def new
    @user = User.new
    #apts = Appartamenti.all    
    #@appartamenti = apts.map { |s| [s.apt, s.apt] }
    @appartamenti = $apts
  end

  def create
    myParams = {}
    myParams = user_params
    myParams[:stato] = "NEW"
    puts "Entering NEW USER #{myParams}"
    user = User.create(myParams)
    if user.save
      puts "User: #{user.id} WAS SAVED"
      AddHistory(user, 'STATO  --> NEW (registrazione nuovo utente)')
      redirect_to login_path
    else
      puts "FAIL to save NEW USER"
      apts = $apts #Appartamenti.all    
      @appartamenti = apts.map { |s| [s.apt, s.apt] }
      render 'new'
    end
  end

  def show #mostra profilo utente
    @user = User.find(params[:user_id])
  end

  def list #crea la lista degli utenti
    params[:sort] ||= 'apt'       #definisco il valore di default
    params[:direction] ||= 'asc'  #definisco il valore di default
    #puts params[:sort] 
    #puts params[:direction]
    @nuovi = User.where(stato: "NEW")  #lista utenti in attesa di approvazione
    @users = User.where.not(stato: "NEW").order(params[:sort] + ' ' + params[:direction]) #lista ordinata utenti in essere
    @stati = [['NEW','NEW'],['INQUILINO','INQUILINO'],['GESTORE','GESTORE'],['ADMIN','ADMIN'],['ARCHIVIATO','ARCHIVIATO']]
    #puts @users.inspect
  end

  def update
    puts "Matteo --> Update User with params: #{params[:id]}"
    user = User.find(params[:id])
    AddHistory(user, 'STATO '+ user.stato + ' --> ' + user_params[:stato])
    user.stato = user_params[:stato]
    user.save
    redirect_to '/utenti'
  end

  def showHistory
    puts "SHOW-HISTORY(params): #{params.inspect} #{params[:format]}"
    user = User.find(params[:format])
    @history = user.history
  end

  def ccommenti
    puts "SHOW-COMMENTI(params): #{params.inspect} #{params[:format]}"
    @user = User.find(params[:format])
  end

  def showCommenti
    #puts "SHOW-COMMENTI(params): #{params.inspect} #{params[:format]}"
    @user = User.find(params[:format])
    #AddRecord(@user, 'commenti', "balle belle")
    userComments = []
    @comments = []
    #userComments = @user.commenti.scan(/.*\n\n/m)
    if (!@user.commenti) 
      @user.commenti = ""
    end
    userComments = @user.commenti.split("\n\n") #separo un commento dall'altro in un array
    #puts "TASK-COMMENTS:"
    #puts userComments.inspect
    # per ogni commento genero l'oggetto estrapolando le varie informazioni
    userComments.each() {|c| 
      c += "\n" # inserisco un "newline" nel caso, per motivi storici, il campo del DB contenga commenti non formattati correttamente
      head = c.match(/.*\n/)[0] # ricavo l'informazione HEAD contenuta nella prima riga
      @comments.push({
        author: head.gsub(/.* by (.*)\n/,'\1'),  # estraggo l'autore da HEAD
        head: head,                      # inserisco HEAD
        body: c.gsub(head, '')           # ricavo il commento vero e proprio rimuovendo la prima riga
      })
    }
    #puts 'MP --> ' + @comments.inspect
  end
  
  def saveCommenti
    #puts "SAVE-COMMENTI(params): #{params.inspect} #{params[:DELbutton]} #{params[:userID]} #{params[:commento]} #{params[:comN]}"
    @user = User.find(params[:ID])
    #puts "SAVE-COMMENTI(user): #{@user.inspect}"
    if(params[:comN] != 'NEW') 
      #puts "SAVING MODIFIED COMMENT N. #{params[:comN]}"
      n = params[:comN].to_i
      del = params[:DELbutton]
      userComments = []
      userComments = @user.commenti.scan(/.*\n.*\n\n/)
      #puts userComments.inspect
      commenti = ""
      userComments.each_with_index() {|c, i| 
        if(i != n) 
          puts "i: " + i.to_s + "n: " + n.to_s
          commenti += c
        else
          puts "DELETING: " + c
        end
      }
      @user.commenti = commenti
    end
    #puts "COMMENTI: " 
    #puts @user.commenti
    if(del != 'DEL')
      AddRecord(@user, 'commenti', params[:commento])
    else
      @user.save
    end
    redirect_to '/utenti'
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :apt, :password, :stato)
  end

  def AddRecord(rec, type, text)
  puts "ADD-RECORD:"
  puts text
  puts "AUTHOR: #{$user.email}" + $user.inspect
  if(! rec[type]) then rec[type] = "" end
  rec[type] = DateTime.now.strftime("%d/%m/%Y  %I:%M%p") + " by " + $user[:email] + "\n" + text.gsub(/\n\n+/,'\n') + "\n\n" + rec[type]
  rec.save
end

  def AddHistory(user, text)
    puts "AUTHOR: #{user[:email]}" 
    if(! user.history) then user.history = "" end
    user.history = DateTime.now.strftime("%d/%m/%Y  %I:%M%p") + " by " + user[:email] + "\n" + text + "\n\n" + user.history
    user.save
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_showCommenti.html.erb
<div class="container" style="padding: 100px;  background-color: coral; text-align: center">
<form action="/saveCommenti" method="POST">
  <textarea name="commenti" data-remote="true" rows="40" cols="50">
    <%= @user.commenti %>
  </textarea>
  <input type="hidden" name="userID" value="<%= @user.id %>">
  <button type="submit" >SAVE</button>
</form>
</div>

app/views/users/_showHistory.html.erb
<textarea readonly style="width: 700px; height: 700px">
<%= @history %>
</textarea>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= simple_form_for user, class: 'clearfix', remote: true  do |f| %>
      <%= f.select(:stato, @stati, {}, {:onchange => 'this.form.submit()', class: "form-control"}) %>
    <% end %>
  </td>
  <td>
    <%= user.apt %>
  </td>
  <td>
    <%= link_to history_path(user), remote: true do %><i class="fa fa-history"></i></i><% end %>
    <%= link_to commenti_path(user), remote: true do %><i class="fa fa-commenting-o"></i><% end %>
  </td>
</tr>

app/views/users/list.html.erb
<div class="container">
  <h2>Nuovi Utenti da Approvare</h2>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>email</th>
          <th>Stato</th>
          <th>APT</th>
          <th>Azioni</th>
        </tr>
      </thead>
      <tbody>
        <% Array(@nuovi).each do |user| %>
          <tr>
            <td>
              <%= user.email %>
            </td>
            <td>
              <%= simple_form_for user, class: 'clearfix', remote: true  do |f| %>
                <%= f.select(:stato, @stati, {}, {:onchange => 'this.form.submit()', class: "form-control"}) %>
              <% end %>
            </td>
            <td>
              <%= user.apt %>
            </td>
            <td>
              <%= link_to history_path(user), remote: true do %>  <i class="icon-time"></i><% end %>
              <%= link_to commenti_path(user), remote: true do %>  <i class="icon-comment"></i><% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h2>Utenti Attivi</h2>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th><%= sortable "email"%></th>
          <th><%= sortable "stato"%></th>
          <th><%= sortable "apt" %> </th>
          <th>Azioni</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: @users %>
      </tbody>
    </table>    
</div>

app/views/users/new.html.erb
<div class="container">

<h1>Registrazione Nuovo Utente</h1>

<%= form_for @user do |f| %>
  <%= f.label :Email %><% if @user.errors.any? %><span class="text-error"> ERRORE Utente già registrato</span><% end %>
  <%= f.email_field :email %><br>
  <%= f.label :apt %>
  <%= f.select(:apt, @appartamenti, {}, {class: "form-control"}) %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Crea Account" %>
<% end %>    
<%= link_to 'LOGIN', login_path %>
</div>

app/views/users/showCommenti.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'tasks/commenti', locals: {comments: @comments, elemento: @user, controller: ''}) %>');
m.modal('show');

function myFunction(p1, p2) {
  document.querySelector('#edit').value = p2.children.item(1).innerHTML;
  selected = document.querySelector('.selected');
  if(selected) {
    selected.style.backgroundColor = "blue";
    selected.classList.remove("selected");
  }
  p2.style.backgroundColor = "red";
  p2.classList.add("selected");
  document.querySelector('#comN').value = p2.id;
  document.querySelector('#del').style.display = "inline";
}


function myNew() {
  document.querySelector('#comN').value = 'NEW'; 
  document.querySelector('#del').style.display = "none";
  selected = document.querySelector('.selected');
  if(selected) {
    selected.style.backgroundColor = "blue";
    selected.classList.remove("selected");
  }
  document.querySelector('#edit').value = "";
}  

app/views/users/showHistory.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'showHistory', locals: {task: @task}) %>');
m.modal('show');